stages:
  - test
  - deploy

test:
  image: node:22-alpine
  stage: test
  script:
    - npm test

pages:
  image: alpine:3.20
  stage: deploy
  needs:
    - test
  script:
    - mkdir public
    - cp index.html public/
    - cp -r src public/src
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
